"""
THIS FILE INCLUDE JUST A BASIC VARIABLE WITH THE REPO ABSOLUTE PATH. THIS IS FILLED WHEN YOU RUN install.sh SCRIPT.
THIS IS DUE SINCE, IF YOU RUN install.sh SCRIPT, YOU CAN THEN LAUNCH THE SCRIPT FROM WHEREVER YOU WANT IN THE FILE SYSTEM.
ANYWAY THE TOOL NEED TO KNOW WHERE TO SAVE FILES FOR JKU INJECTIONS.

"""

#[CONFIGS]
